language: python

python:
  - "3.6"

install:
  - pip3 install -r requirements.txt

script:
  - pytest tests/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
