language: python

python:
  - "3.6"

install:
  - pip3 install -r requirements.txt

script:
  - pytest --cov-config .coveragerc tests.py --pep8 tests.py --cov-report  term-missing --cov-branch --cov=tests

after_success:
  - coveralls
